version: 2

models:
  - name: stg_telegram_messages
    description: Cleaned telegram messages
    columns:
      - name: id
        tests:
          - not_null
          #- unique
      - name: channel
        tests:
          - not_null
      - name: message_time
        tests:
          - not_null
